name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate templates
        run: templ generate

      - name: Build binary
        run: go build -o golang-initializr

      # Авто-включаем GitHub Pages
      - name: Configure Pages
        uses: actions/configure-pages@v3
        with:
          enablement: auto

      # Загружаем статику (пример: папка static)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path:
            ./static # <- убедитесь, что здесь именно та папка,
            #    куда templ/svelte/другой билд складывает файлы

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
